name = "studymate-web"
main = "worker/cf_worker.py"
compatibility_date = "2026-04-13"
compatibility_flags = ["python_workers"]
workers_dev = true

[assets]
directory = "./static"
binding = "ASSETS"
run_worker_first = ["/", "/login", "/logout", "/check-userid", "/signup", "/study*", "/mypage", "/myposts", "/comment*", "/chats", "/update_profile", "/profile*", "/enrollment*"]

[[d1_databases]]
binding = "DB"
database_name = "studymate-db"
database_id = "da001973-efd4-4229-9062-bf46e02f51c3"